# Generated by Django 5.2.1 on 2025-05-17 19:40

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=90)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('London', 'London'), ('Paris', 'Paris'), ('Rome', 'Rome'), ('Berlin', 'Berlin'), ('Madrid', 'Madrid'), ('Amsterdam', 'Amsterdam'), ('Vienna', 'Vienna'), ('Prague', 'Prague'), ('Budapest', 'Budapest'), ('Barcelona', 'Barcelona'), ('Lisbon', 'Lisbon'), ('Dublin', 'Dublin'), ('Athens', 'Athens'), ('Copenhagen', 'Copenhagen'), ('Stockholm', 'Stockholm'), ('Oslo', 'Oslo'), ('Brussels', 'Brussels'), ('Helsinki', 'Helsinki'), ('Warsaw', 'Warsaw'), ('Zurich', 'Zurich'), ('Munich', 'Munich'), ('Milan', 'Milan'), ('Frankfurt', 'Frankfurt'), ('Edinburgh', 'Edinburgh'), ('Nice', 'Nice'), ('Florence', 'Florence'), ('Krakow', 'Krakow'), ('Porto', 'Porto'), ('Geneva', 'Geneva'), ('Naples', 'Naples'), ('Seville', 'Seville'), ('Lyon', 'Lyon'), ('Cologne', 'Cologne'), ('Valencia', 'Valencia'), ('Bratislava', 'Bratislava'), ('Riga', 'Riga'), ('Tallinn', 'Tallinn'), ('Vilnius', 'Vilnius'), ('Luxembourg', 'Luxembourg'), ('Ljubljana', 'Ljubljana'), ('Reykjavik', 'Reykjavik'), ('Bucharest', 'Bucharest'), ('Sofia', 'Sofia'), ('Belgrade', 'Belgrade'), ('Zagreb', 'Zagreb'), ('Sarajevo', 'Sarajevo'), ('Skopje', 'Skopje'), ('Tirana', 'Tirana'), ('Podgorica', 'Podgorica'), ('Chisinau', 'Chisinau'), ('San Marino', 'San Marino'), ('Monaco', 'Monaco'), ('Andorra la Vella', 'Andorra la Vella'), ('Valletta', 'Valletta'), ('Nicosia', 'Nicosia'), ('The Hague', 'The Hague'), ('Rotterdam', 'Rotterdam'), ('Antwerp', 'Antwerp'), ('Ghent', 'Ghent'), ('Hamburg', 'Hamburg'), ('Düsseldorf', 'Düsseldorf'), ('Bordeaux', 'Bordeaux'), ('Turin', 'Turin'), ('Bologna', 'Bologna'), ('Palermo', 'Palermo'), ('Verona', 'Verona'), ('Leeds', 'Leeds'), ('Manchester', 'Manchester'), ('Birmingham', 'Birmingham'), ('Liverpool', 'Liverpool'), ('Sheffield', 'Sheffield'), ('Newcastle', 'Newcastle'), ('Glasgow', 'Glasgow'), ('Stuttgart', 'Stuttgart'), ('Dresden', 'Dresden'), ('Nuremberg', 'Nuremberg'), ('Innsbruck', 'Innsbruck'), ('Salzburg', 'Salzburg'), ('Graz', 'Graz'), ('Basel', 'Basel'), ('Lucerne', 'Lucerne'), ('Lausanne', 'Lausanne'), ('Bern', 'Bern'), ('Cannes', 'Cannes'), ('Toulouse', 'Toulouse'), ('Marseille', 'Marseille'), ('Malaga', 'Malaga'), ('Alicante', 'Alicante'), ('Granada', 'Granada'), ('Cordoba', 'Cordoba'), ('Bilbao', 'Bilbao'), ('San Sebastian', 'San Sebastian'), ('Lille', 'Lille'), ('Strasbourg', 'Strasbourg'), ('Utrecht', 'Utrecht'), ('Eindhoven', 'Eindhoven'), ('Brno', 'Brno'), ('Wroclaw', 'Wroclaw'), ('Gdansk', 'Gdansk')], max_length=80)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('selling_price', models.FloatField()),
                ('discounted_prie', models.FloatField()),
                ('short_description', tinymce.models.HTMLField(max_length=110)),
                ('description', tinymce.models.HTMLField()),
                ('category', models.CharField(choices=[('Mobile', 'MEN WEAR'), ('Laptop', 'WOMAN WEAR'), ('ElectronicAccessories', 'Accessories')], max_length=30)),
                ('product_image', models.ImageField(upload_to='productimg')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.brand')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPlaced',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveBigIntegerField(default=1)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel')], default='Pending', max_length=60)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveBigIntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=150)),
                ('verify', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
